Add 'channel_settings' to the MockContext
anaconda_auth introduced using the channel_settings config from
the context in https://github.com/anaconda/anaconda-auth/pull/175/files.

So, when running tests, the mock context must be able to provide
this configuration. Otherwise, it will fail with the error

```
AttributeError: 'MockContext' object has no attribute 'channel_settings'
```