Fix AttributeError when generating trash filename
Problem:
- str object has no attribute 'splitext'
- Using bracket instead of parenthesis for function call
- os.path.splitext should be used but wasn't

Solution:
- Use os.path.splitext() instead of str.splitext
- Use proper function call syntax

Fixes #15760