fetch: Timeout tuples do not work for ftp
This is a bug in the interaction between requests and ftplib but
we can work around it anyway.

Before this change, ftp downloads would fail on Python 3.5 with:

  File ../conda/conda/conda/fetch.py, line 378, in download
    resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3.05, 27))
  File ../lib/python3.5/site-packages/requests/sessions.py, line 487, in get
    return self.request('GET', url, **kwargs)
  File ../lib/python3.5/site-packages/requests/sessions.py, line 475, in request
    resp = self.send(prep, **send_kwargs)
  File ../lib/python3.5/site-packages/requests/sessions.py, line 585, in send
    r = adapter.send(request, **kwargs)
  File ../conda/conda/conda/connection.py, line 306, in send
    self.conn.connect(host, port, timeout)
  File ../lib/python3.5/ftplib.py, line 153, in connect
    source_address=self.source_address)
  File ../lib/python3.5/socket.py, line 699, in create_connection
    sock.settimeout(timeout)
TypeError: an integer is required (got type tuple)